# Generated by Django 4.1 on 2022-08-29 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(default='media/images/avatar.jpg', upload_to='media/images/')),
                ('seller', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=b'I01\n')),
                ('category', models.CharField(choices=[('Stationary', 'Stationary'), ('Fashion', 'Fashion'), ('Electronic device', 'Electronic device'), ('Food', 'Food')], max_length=80, null=b'I01\n')),
                ('quantity', models.PositiveBigIntegerField(null=b'I01\n')),
                ('price', models.PositiveBigIntegerField(null=b'I01\n')),
                ('desc', models.CharField(max_length=1000, null=b'I01\n')),
                ('image', models.ImageField(upload_to='media/images/')),
                ('seller', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.seller_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveBigIntegerField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
