# Generated by Django 4.1 on 2022-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'Stationary'), ('Fashion', 'Fashion'), ('Electronic device', 'Electronic device'), ('Food', 'Food'), ('Babies & Toys', 'Babies & Toys')], max_length=80, null=b'I01\n'),
        ),
    ]
